language: elixir

elixir: 1.8.2
otp_release: 21.3.7

dist: xenial

services:
- postgresql

before_script:
- sudo apt-get install
- psql -c 'create database londibot_repo;' -U postgres

script:
- MIX_ENV=test mix coveralls.travis --exclude callout

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
