language: elixir

elixir: 1.8.2
otp_release: 21.3.7

dist: xenial

services:
- postgresql

before_script:
- sudo apt-get install
- psql -c 'create database londibot_repo;' -U postgres

script:
- MIX_ENV=test mix coveralls.travis --exclude callout

deploy:
  - provider: script
    script:
      - git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
      - mix test && git push -f gigalixir HEAD:refs/heads/master
    on:
      branch: master
