language: elixir

elixir:
- 1.8.0

dist: xenial

services:
- postgresql

before_script:
- sudo apt-get install
- psql -c 'create database londibot_repo;' -U postgres

script:
- MIX_ENV=test mix coveralls.travis
